#!/usr/bin/env python3
"""EDA-003 Stage 2 -> UVM -> Stage 3 -> Reviewer integration."""
from __future__ import annotations

import copy
import json
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

import yaml

from contracts.validator import load_document
from runtime.project_job import ProjectJobWorkflow
from tests.agent_runtime.test_project_job_workflow import (
    FakeProvider, FakeReviewerProvider, SPEC,
)
from application.generation import GenerateStage3Input
from application.uvm_generation import load_effective_uvm_pass
from runtime.errors import ProjectJobError
from runtime.staged_workflow import StagedProjectWorkflow
from scripts.run_project_job import generation_xcelium


class Eda003Generator(FakeProvider):
    @staticmethod
    def stage3(payload):
        manifest = payload["generated_testcase_manifest"]
        units = []
        implemented = []
        for item in manifest["testcases"]:
            testcase_id = item["testcase_id"]
            implemented.append(testcase_id)
            units.append({
                "role": "TESTCASE", "testcase_ids": [testcase_id],
                "content": (
                    "class {name} extends base_test;\n"
                    "  task execute_testcase();\n"
                    "    logic clk; logic y;\n"
                    "    clk = 1'b0; if (y !== clk) `uvm_fatal(\"AC_TINY_LOW_FAIL\", \"y\")\n"
                    "    clk = 1'b1; if (y !== clk) `uvm_fatal(\"AC_TINY_HIGH_FAIL\", \"y\")\n"
                    "  endtask\nendclass\n").format(name=item["uvm_class"]),
            })
        return {"code_units": units, "assembly": list(range(len(units))),
                "implemented_testcase_ids": implemented,
                "skipped_testcases": []}


class Eda003RepairGenerator(Eda003Generator):
    provider_id = "fake-repair-provider"
    model_id = "fake-repair-model"


class FakeUvmProvider:
    provider_id = "fake-uvm-provider"
    model_id = "openai/gpt-5.6-sol"

    def __init__(self):
        self.calls = 0
        self.requests = []

    def probe(self):
        return {
            "schema_version": "1.0", "provider_id": self.provider_id,
            "model_id": self.model_id, "status": "PASS",
            "tool_call_capable": True, "provider_version": "test",
            "diagnostics": [],
        }

    def restore_probe(self, _probe):
        return None

    def select_tools(self, request):
        self.calls += 1
        self.requests.append(copy.deepcopy(request))
        payload = json.loads(request["messages"][1]["content"])
        replacements = [{
            "logical_path": path,
            "content": "// generated by independent UVM role\n",
        } for path in payload["immutable_generation_context"][
            "generated_file_slots"]]
        prior_results = [
            json.loads(message["content"].split("\n", 1)[1])
            for message in request["messages"][2:]
            if message.get("role") == "USER" and
            message.get("content", "").startswith("TOOL_RESULT\n")
        ]
        if not prior_results:
            tool_name = "write_uvm_replacements"
            arguments = {"replacements": replacements}
        elif prior_results[-1]["tool_name"] == "write_uvm_replacements":
            tool_name, arguments = "run_xcelium_compile", {}
        else:
            tool_name, arguments = "finish_task", {}
        return {
            "schema_version": "1.0",
            "request_id": request["request_id"],
            "operation": "SELECT_TOOLS", "finish_reason": "TOOL_CALLS",
            "content": "", "model_id": self.model_id,
            "provider_metadata": {
                "provider_id": self.provider_id,
                "response_id": "RESP.UVM.{:03d}".format(self.calls),
                "provider_status": "completed",
            },
            "usage": {"input_tokens": 1, "output_tokens": 1},
            "diagnostics": [],
            "tool_calls": [{
                "call_id": "CALL.UVM.{:03d}".format(self.calls),
                "name": tool_name,
                "arguments": arguments,
            }],
        }


class Eda003ProjectIntegrationTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        (self.root / "result").mkdir()
        (self.root / "config").mkdir()
        (self.root / "uvm").mkdir()
        (self.root / "spec.md").write_text(SPEC)
        (self.root / "tiny.sv").write_text(
            "module tiny(input logic clk, output logic y); "
            "assign y=clk; endmodule\n")
        (self.root / "uvm/pkg.sv").write_text(
            "package p; endpackage\n")
        (self.root / "uvm/base_test.svh").write_text(
            "class base_test; endclass\n")
        base = {
            "schema_version": "1.0", "provider_kind": "DASHSCOPE",
            "provider_id": "fake-project-provider",
            "model_id": "fake-project-model",
            "endpoint": "https://dashscope.aliyuncs.com/compatible-mode/v1",
            "auth_env": "DASHSCOPE_API_KEY",
            "api_version": "chat-completions-v1",
            "tool_calls_required": True, "store": False,
            "timeout_seconds": 60, "max_retries": 0,
            "max_output_tokens": 8192, "enable_thinking": False,
        }
        reviewer = {**base, "provider_id": "fake-project-reviewer",
                    "model_id": "fake-reviewer-model"}
        repair_generator = {**base, "provider_id": "fake-repair-provider",
                            "model_id": "fake-repair-model"}
        uvm = {**base, "schema_version": "2.0",
               "provider_kind": "OPENROUTER",
               "provider_id": "fake-uvm-provider",
               "model_id": "openai/gpt-5.6-sol",
               "endpoint": "https://openrouter.ai/api/v1",
               "auth_env": "OPENAI_API_KEY",
               "api_version": "responses-v1"}
        uvm.pop("enable_thinking")
        uvm["reasoning_effort"] = "medium"
        for name, value in (("generator", base), ("reviewer", reviewer),
                            ("repair_generator", repair_generator),
                            ("uvm", uvm)):
            (self.root / "config/{}.yaml".format(name)).write_text(
                yaml.safe_dump(value, sort_keys=False))
        profile = {
            "schema_version": "1.0", "profile_id": "PROJECT_AGENT_PROFILE.TEST",
            "initial": {"stage1": "config/generator.yaml",
                        "stage2": "config/generator.yaml",
                        "uvm": "config/uvm.yaml",
                        "stage3": "config/generator.yaml"},
            "repair": {"orchestrator": "config/generator.yaml",
                       "stage1": "config/generator.yaml",
                       "stage2": "config/generator.yaml",
                       "uvm": "config/uvm.yaml",
                       "stage3": "config/repair_generator.yaml"},
            "review": {"initial": "config/reviewer.yaml",
                       "final": "config/reviewer.yaml"},
        }
        (self.root / "config/agents.yaml").write_text(
            yaml.safe_dump(profile, sort_keys=False))

    def tearDown(self):
        self.temp.cleanup()

    def test_generation_runner_builds_uvm_with_framework_elaboration_top(self):
        calls = []

        class Adapter:
            def build_only(self, execution_id, configuration):
                calls.append((execution_id, configuration))
                return {"execution_status": "PASS", "exit_code": 0}

        manifest = {
            "job_id": "JOB.PROJECT.TINY.EDA003",
            "rtl": {"sources": [{"baseline_path": "tiny.sv"}],
                    "top": "tiny"},
            "eda": {"timeout_seconds": 60},
        }
        request = {
            "cycle_id": "initial", "attempt": 1, "tool_run": 1,
            "sources": [{
                "logical_path": "uvm/pkg.sv",
                "path": "staging/generated/uvm/initial/attempt-001/effective/uvm/pkg.sv",
            }],
            "framework_sources": [{
                "logical_path":
                    "framework/dv_uvm_generation_elaboration_top.sv",
                "path": (
                    "audit/uvm_generation/initial/attempt-001/"
                    "xcelium-run-001.elaboration_top.sv"),
            }],
            "top": "dv_uvm_generation_elaboration_top",
        }
        with patch(
                "scripts.run_project_job.XceliumAdapter.from_preloaded_environment",
                return_value=Adapter()):
            generation_xcelium(manifest, Path("unused"), request)

        self.assertEqual(1, len(calls))
        configuration = calls[0][1]
        self.assertEqual(
            "dv_uvm_generation_elaboration_top", configuration.top)
        self.assertEqual((
            "result/jobs/JOB.PROJECT.TINY.EDA003/staging/generated/uvm/"
            "initial/attempt-001/effective/uvm/pkg.sv",
            "result/jobs/JOB.PROJECT.TINY.EDA003/audit/uvm_generation/"
            "initial/attempt-001/xcelium-run-001.elaboration_top.sv",
        ), configuration.sources)
        self.assertIn(
            "result/jobs/JOB.PROJECT.TINY.EDA003/staging/generated/uvm/"
            "initial/attempt-001/effective/uvm",
            configuration.include_dirs)
        self.assertNotIn("tiny.sv", configuration.sources)

    def test_independent_uvm_pass_tree_is_the_only_stage3_context(self):
        workspace_uvm_before = {
            path: (path.read_bytes(), path.stat().st_mtime_ns)
            for path in sorted((self.root / "uvm").rglob("*"))
            if path.is_file()
        }
        generator = Eda003Generator()
        reviewer = FakeReviewerProvider()
        uvm = FakeUvmProvider()
        repair_generator = Eda003RepairGenerator()
        workflow = ProjectJobWorkflow(
            self.root, self.root / "result",
            role_providers={
                "initial.stage1": generator, "initial.stage2": generator,
                "initial.uvm": uvm, "initial.stage3": generator,
                "repair.stage3": repair_generator,
                "review.initial": reviewer,
            },
            uvm_build_runner=lambda _value, _root, _request: {
                "execution_status": "PASS", "exit_code": 0,
                "stdout": "build passed", "stderr": "", "logs": [],
            })
        submission = {
            "schema_version": "2.0", "job_id": "JOB.PROJECT.TINY.EDA003",
            "project_id": "PROJECT.TINY", "spec": {"sources": ["spec.md"]},
            "rtl": {"sources": ["tiny.sv"], "top": "tiny", "parameters": {}},
            "uvm_testcase_context": {
                "files": ["uvm/pkg.sv", "uvm/base_test.svh"],
                "generated_files": ["uvm/base_test.svh"],
            },
            "agent_profile": "config/agents.yaml",
            "eda": {"profile_id": "EDAPROFILE.XCELIUM.PROJECT.V1",
                    "timeout_seconds": 60},
            "input_authority": {"actor_type": "HUMAN", "identity": "owner",
                "roles": ["SPEC_OWNER", "DESIGN_OWNER"], "decision": "APPROVE"},
        }
        first = workflow.start(submission)
        job = self.root / "result/jobs" / submission["job_id"]
        form = load_document(job / first["owner_review_path"])
        form["actor"]["identity"] = "owner"
        for scenario in form["scenarios"]:
            scenario["routing"]["destination"] = \
                "AC_TESTCASE_MAP_AND_TESTCASE"
        result = workflow.route_scenarios(submission, form)
        self.assertEqual("AWAITING_HUMAN_REVIEW", result["state"])
        self.assertEqual(3, uvm.calls)
        stage3_request = next(item for item in generator.requests
                              if item["metadata"]["stage"] == "TESTCASE")
        payload = json.loads(stage3_request["messages"][1]["content"])
        context = payload["uvm_testcase_context"]
        by_path = {item["logical_path"]: item["content"]
                   for item in context["files"]}
        self.assertEqual("// generated by independent UVM role\n",
                         by_path["uvm/base_test.svh"])
        self.assertEqual("package p; endpackage\n", by_path["uvm/pkg.sv"])
        self.assertNotIn("baseline_uvm_files", payload)
        self.assertEqual(
            context["effective_uvm_root"],
            result["bundle_fingerprints"]["effective_uvm"])
        self.assertTrue((job / "transcripts/uvm_generation/").is_dir())
        self.assertTrue((job / "transcripts/stage3/").is_dir())
        generator_calls = generator.calls
        replay = workflow.start(submission)
        self.assertEqual("AWAITING_HUMAN_REVIEW", replay["state"])
        self.assertEqual(
            context["effective_uvm_root"],
            replay["bundle_fingerprints"]["effective_uvm"])
        self.assertEqual(generator_calls, generator.calls)
        self.assertEqual(3, uvm.calls)

        manifest = load_document(
            job / "input_baseline/project_input_manifest.json")
        map1 = load_document(job / result["scenario_ac_map_path"])
        map2 = load_document(job / result["ac_testcase_map_path"])
        candidate = load_document(job / result["candidate_metadata_path"])
        staged = StagedProjectWorkflow(workflow)
        spec_evidence, _, spec_fingerprint = staged._spec(manifest)
        testcases, shards = staged._load_shards(job, map2)
        effective_files, effective_root = load_effective_uvm_pass(
            job, job_id=manifest["job_id"],
            input_fingerprint=manifest["input_fingerprint"],
            cycle_id="initial", stage2_root=map2["artifact_fingerprint"],
            error=ProjectJobError)
        workflow._probe_provider(job, "repair.stage3")
        repaired = staged.generate_stage3_handler.handle(GenerateStage3Input(
            manifest, job, spec_evidence, spec_fingerprint, map1, map2,
            testcases, shards, 1, workflow._budget(), prior=candidate,
            issues=[{"finding_id": "F.REPAIR", "stage": "STAGE_3"}],
            effective_uvm_files=effective_files,
            effective_uvm_root=effective_root,
            profile_section="repair"))
        self.assertEqual(1, repaired.artifact["revision"])
        self.assertEqual("fake-repair-provider",
                         repaired.artifact["provider"]["provider_id"])
        self.assertEqual("repair.stage3",
            repair_generator.requests[-1]["metadata"]["agent_profile_role"])
        self.assertEqual(workspace_uvm_before, {
            path: (path.read_bytes(), path.stat().st_mtime_ns)
            for path in sorted((self.root / "uvm").rglob("*"))
            if path.is_file()
        })


if __name__ == "__main__":
    unittest.main()
